export const icons = {
    default: null,
    search: require('./source/ic_search.png'),
    arrowRight: require('./source/arrow-right.png'),
    arrowLeft: require('./source/arrow-left.png'),
    plus: require('./source/plus.png'),
    clock: require('./source/clock.png'),
    vibrate: require('./source/vibrate.png'),
    wifi: require('./source/wifi.png'),
    power: require('./source/power.png'),
    signal: require('./source/signal.png'),
    wi_fi: require('./source/wi_fi.png'),
    ring: require('./source/ring.png'),
    flash: require('./source/flash.png'),
    save_power: require('./source/save_power.png'),
    data: require('./source/data.png'),
    bluetooth: require('./source/bluetooth.png'),
    moon: require('./source/moon.png'),
    air_mode: require('./source/air_mode.png'),
    location: require('./source/location.png'),
    rotate: require('./source/rotate.png'),
    share_data: require('./source/share_data.png'),
    auto_light: require('./source/light_auto.png'),
    notification: require('./source/notification.png'),
    lock: require('./source/security.png'),
    data_pie: require('./source/pie_data.png'),
    chat: require('./source/chat.png'),
    folder: require('./source/folder.png'),
    device: require('./source/device.png'),
    language: require('./source/language.png'),
    ask_q: require('./source/ask_q.png'),
    faq: require('./source/faq.png'),
    privacy: require('./source/privacy.png'),
    home: require('./source/home.png'),
    friend: require('./source/friend.png'),
    video: require('./source/video.png'),
    shop: require('./source/Shop.png'),
    notification2: require('./source/notification2.png'),
    menu: require('./source/Menu.png'),
    expand:require('./source/expand.png'),
    collapse:require('./source/collapse.png')
};

export type IconTypes = keyof typeof icons;
