export const APP_SCREEN = {
    MAIN: "MAIN",
    BOUNCING: "BOUNCING",
    TIMING: "TIMING",
    DYNAMIC_SPRING: "DYNAMIC_SPRING",
    DECAY: "DECAY",
    FACEBOOK_STORY: 'FACEBOOK_STORY',
    WHEEL_PICKER: "WHEEL_PICKER",
    JELLY_LIST: 'JELLY_LIST',
    TRANSITION: "TRANSITION",
    WAVY: "WAVY",
    TELEGRAM: "TELEGRAM",
    SHARE_ELEMENT: "SHARE_ELEMENT",
    CIRCLE_MENU: "CIRCLE_MENU",
    YOU_TUBE: 'YOU_TUBE',
    WAVE: 'WAVE',
    INDICATOR: 'INDICATOR'
}